### PR TITLE
special character supported as hotkeys fixes #1

### LINKED ISSUE #1: special characters not recognized as keys
Hi! First of all congrats on this tiny but very useful library. I'm using it on a new project with success.
One issue though is that I can't use hotkeys with special characters, such as `cmd-[` or `cmd-'` since the regular expression used to match those is using `\w` which does not include those characters: https://github.com/bpeacock/onKey/blob/d67e3f9ec616528cdab43a00d6640ddc012e73d8/src/Event.js#L84

My suggestion is to add all special characters to the regular expression and to define `+` as the default hotkey connector, since `-` can be used as hotkey.

### PR DESCRIPTION
**Pull request by drochetti**
My main goal is to support combination with special keys such as `-`, `'` and `/`
The current regular expression i using `\w` which ignore those characters.
Feel free to suggest any change to my fix.
This should fix #1

### CODE REVIEW

**Comment by bpeacock** [comment]
Thank you for contributing, Daniel!  The + hotkey connector makes sense to me but lets increment the minor version number to make this v0.1.0 since it is a breaking syntactical change.  Also, can you fix the tests that broke with your change and add test coverage for special characters?  It should be as simple as changing the syntax used in the tests.  Then, I will be happy to merge your changes.  Thank you again.

**Comment by drochetti** [comment]
@bpeacock sorry about that!
Looks ok now. I added two new tests for the special keys case.

I bumped the version as suggested and added a note on README about the syntax change.

**Comment by drochetti** [comment]
Hi @bpeacock 
Any plans on merging this pull request? Thanks!

**Comment by bpeacock** [comment]
Just did @drochetti, sorry I missed your first message!

**Comment by drochetti** [comment]
No problem @bpeacock 
Thanks a lot!

**Pull request merged**
